### ISSUE TITLE
ControlNET?

### ISSUE THREAD

**Issue by g1thub2020** [AnonymousCervine/gradio-gallery-base64image-monkeypatch#1]
I noticed that outputs generated with ControlNET no longer had the index title. I checked the AppData/Local/Temp folder and sure enough found the tmp images. Would it be possible to have this script also apply to ControlNET? It's no hassle to manually delete them but I'd rather not wear out my SSD if possible.

**Comment by AnonymousCervine** [comment]
My sympathies—I know the pain of unnecessary read/writes! Even if realistically, modern SSDs can generally survive this sort of level of abuse just fine. (Well. I say that *assuming* that by the nature of AI generation that you're generating no more than a good few MB per second on average at the absolute most, which if going *constantly* all day is just about the same number of bytes written as most people might give hibernating/hybrid-sleeping to an SSD a couple times a day, which nowadays we can get away with pretty comfortably without stressing an SSD's lifespan unduly—so, even though that's not a strict apples-to-apples comparison, I probably wouldn't be overly-concerned, unless the SSD in question is reasonably old. Which doesn't mean it's not annoying to have infinitesimal bits of ssd lifespan shaved off for no good reason!)

Anyway, I'm aware of what ControlNet is but I haven't used it yet. I won't promise anything, but can I get some additional context? "No longer had the index title"? What index title?

And what interface are you using for ControlNet? The [base ControlNet repo](https://github.com/lllyasviel/ControlNet)? Or something like an [extension](https://github.com/Mikubill/sd-webui-controlnet) for the SD webui project?

**Comment by g1thub2020** [comment]
I appreciate you looking into it. I'm using the SD-webui with that extension you linked.

I should've written name rather than title, sorry. I meant the name of a generated image if you were to save it from the webui browser. Without your script, the image is named something like tmpx8pmlcdf.png. With your script, the images instead are named index.png. I noticed that when saving a few ControlNET test outputs they were saving as tmp again which led me to check the temp folder.

**Comment by AnonymousCervine** [comment]
Good news! It was just that the ControlNet extension used one of the formats I didn't have support for in my bare-bones implementation here (ControlNet returns numpy arrays of image data for the supplementary data it generates—like, say, the canny edge detection images for instance—instead of PIL (python image library) data and so my code would fail and fall back to default behaviour).

It should work now. (That said, it's not like I tested every single thing in ControlNet; do let me know if you still run into issues!)
